defaults:
  - _sam40_common_default
  - _self_

name: sam40_arithmetic_mirror
report_dir: _preparation/sam40_arithmetic_mirror

mne_bids_pipeline:
  task: [relax, arithmetic, mirror]
  deriv_root: ${..dataset_dir}/derivatives/mne-bids-pipeline/relax-arithmetic-mirror
