defaults:
  - _sam40_common_default
  - _self_

name: sam40_all
report_dir: _preparation/sam40_all

mne_bids_pipeline:
  task: [relax, stroop, arithmetic, mirror]
  deriv_root: ${..dataset_dir}/derivatives/mne-bids-pipeline/relax-stroop-arithmetic-mirror
