"""Package a self-contained PLOS ONE submission project from a manuscript source.

PLOS uploads every figure and every supporting-information item as its own file,
while the manuscript file carries only a reference to them
(https://journals.plos.org/plosone/s/figures,
https://journals.plos.org/plosone/s/supporting-information). The editable
manuscript keeps both embedded so that the working PDF stays readable, so this
script is the one place where the two are separated:

  * every ``\\includegraphics`` line becomes an upload note, and the figure's
    pre-rendered TIFF (written by write_article_artifacts in src/analysis.py)
    is copied to ``figures/Fig<N>.tif`` in ``\\includegraphics`` order;
  * every ``\\input`` inside the Supporting information section becomes a PLOS
    legend paragraph, and the item itself is written out as a standalone
    ``S<N>_<Type>.tex`` that compiles on its own;
  * every remaining ``\\input`` is expanded in place.
"""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path


PLOS_SOURCE_DIR = Path(os.environ["PLOS_SOURCE_DIR"]).resolve()
PLOS_OUTPUT_DIR = Path(os.environ["PLOS_OUTPUT_DIR"]).resolve()

# Both skip commented-out lines; only \includegraphics needs its indent kept.
INPUT_PATTERN = re.compile(r"^(?!\s*%)\s*\\input\{(?P<path>[^}]+)}\s*(?:%.*)?\Z")
GRAPHICS_PATTERN = re.compile(
    r"^(?!\s*%)(?P<indent>\s*)\\includegraphics(?:\[[^]]*])?\{(?P<path>[^}]+)}\s*(?:%.*)?\Z"
)
SUPPORTING_SECTION_PATTERN = re.compile(r"^\s*\\section\*\{Supporting information}\s*\Z")

# PLOS names supporting items by the kind of content they hold, and numbers each
# kind from 1. Anything that is neither a float nor a figure is an "S<N> File".
SUPPORTING_ITEM_TYPES = ((r"\begin{table}", "Table"), (r"\begin{figure}", "Fig"))

# A supporting item is uploaded on its own, so it cannot rely on the manuscript
# preamble. This reproduces the part of it the generated tables actually use.
# The geometry matters: the tables size their \tabcolsep off \textwidth, and the
# manuscript reaches the Supporting information section under a \newgeometry of
# left=1in,right=1in, i.e. a 6.5in text block rather than the 5.25in set in the
# preamble. Compiling them at any other width would silently reflow the columns.
SUPPORTING_ITEM_PREAMBLE = r"""%% Generated by python_project/scripts/prepare_plos_submission.py.
%% Do not edit: rerun `make prepare-plos-submission` in latex_documents/ instead.
\documentclass[10pt,letterpaper]{article}
\usepackage[top=0.85in,left=1in,right=1in,footskip=0.75in]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{textcomp,marvosym}
\usepackage[nopatch=eqnum]{microtype}
\DisableLigatures[f]{encoding = *, family = * }
\usepackage[table]{xcolor}
\usepackage{array,booktabs,longtable,float}
\usepackage{multirow}
\usepackage{setspace}
\usepackage{graphicx}
\newcolumntype{+}{!{\vrule width 2pt}}
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\raggedright
\setlength{\parindent}{0.5cm}
\pagestyle{empty}
\begin{document}
"""


def expand_inputs(text: str, directory: Path) -> list[str]:
    expanded = []
    for line in text.splitlines(keepends=True):
        match = INPUT_PATTERN.match(line)
        if not match:
            expanded.append(line)
            continue
        expanded.extend(expand_inputs(*read_input(match, directory)))
    return expanded


def read_input(match: re.Match[str], directory: Path) -> tuple[str, Path]:
    """Resolve one \\input match against the directory holding the including file."""
    included = directory / match.group("path")
    if not included.suffix:
        included = included.with_suffix(".tex")
    if not included.is_file():
        raise SystemExit(f"input file not found: {included}")
    return included.read_text(encoding="utf-8"), included.parent


def take_braced_group(text: str, start: int) -> str:
    """Return the balanced {...} group whose opening brace is at text[start]."""
    depth = 0
    for index in range(start, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:index]
    raise SystemExit(f"unbalanced braces after: {text[start:start + 60]!r}")


def split_caption(body: str, origin: Path) -> tuple[str, str]:
    """Split a supporting item into its caption text and the body without it.

    The caption becomes the legend that stays in the manuscript, and the body
    becomes the uploaded file, so neither may keep the other's copy: a caption
    left in the uploaded file would print a stray "Table 1" that contradicts the
    legend's "S1 Table".
    """
    caption_start = body.find(r"\caption{")
    if caption_start < 0:
        raise SystemExit(f"no \\caption in supporting item: {origin}")
    caption = take_braced_group(body, caption_start + len(r"\caption"))
    caption_end = caption_start + len(r"\caption{") + len(caption) + 1
    stripped = body[:caption_start] + body[caption_end:]
    # \label points at a float number the standalone file no longer prints.
    stripped = re.sub(r"^\s*\\label\{[^}]*}\s*\n", "", stripped, flags=re.MULTILINE)
    return caption.strip(), stripped


def supporting_item_type(body: str) -> str:
    return next((name for marker, name in SUPPORTING_ITEM_TYPES if marker in body), "File")


def externalize_supporting_items(lines: list[str], source: Path) -> tuple[list[str], dict[str, str]]:
    """Replace \\input lines after the Supporting information heading with legends.

    Returns the rewritten manuscript lines and the standalone files to write,
    keyed by their PLOS file name.
    """
    for index, line in enumerate(lines):
        if SUPPORTING_SECTION_PATTERN.match(line):
            break
    else:
        return lines, {}

    counts: dict[str, int] = {}
    rewritten, files = lines[:index + 1], {}
    for line in lines[index + 1:]:
        match = INPUT_PATTERN.match(line)
        if not match:
            rewritten.append(line)
            continue
        text, directory = read_input(match, source)
        body = "".join(expand_inputs(text, directory))
        if r"\includegraphics" in body:
            # Only the manuscript's own figures are repackaged, into
            # figures/Fig<N>.tif. A supporting item carrying a graphic would
            # keep pointing at the source tree and its standalone file would not
            # compile from the package, so say so instead of writing it out.
            raise SystemExit(
                f"{source / match.group('path')} embeds a graphic; supporting items with "
                "figures are not repackaged yet. Their image has to be copied next to the "
                "item as S<N>_Fig and the path rewritten, and PLOS uploads it under the "
                "Supporting Information file type rather than as a Fig<N>.tif figure."
            )
        item_type = supporting_item_type(body)
        counts[item_type] = counts.get(item_type, 0) + 1
        name = f"S{counts[item_type]}_{item_type}"
        caption, body = split_caption(body, source / match.group("path"))
        # The legend format PLOS prescribes: the item label alone in the
        # paragraph heading, then the bold title sentence from the caption.
        rewritten.append(
            f"\\paragraph*{{S{counts[item_type]} {item_type}.}}\n"
            f"\\label{{{name}}}\n"
            f"{caption}\n\n"
        )
        files[f"{name}.tex"] = f"{SUPPORTING_ITEM_PREAMBLE}\n{body.strip()}\n\n\\end{{document}}\n"
    return rewritten, files


def main() -> None:
    source, output = PLOS_SOURCE_DIR, PLOS_OUTPUT_DIR
    # initial_submission/ uses main.tex, revision/manuscript_clean/ uses manuscript.tex.
    main_tex = next((source / name for name in ("main.tex", "manuscript.tex")
                      if (source / name).is_file()), None)
    if main_tex is None:
        raise SystemExit(f"main.tex/manuscript.tex not found in: {source}")
    if source.is_relative_to(output):
        raise SystemExit(f"OUTPUT must not contain SOURCE: {output}")

    # Supporting items go first: they are lifted whole, before the \input lines
    # around them are flattened into the manuscript.
    manuscript = main_tex.read_text(encoding="utf-8").splitlines(keepends=True)
    manuscript, supporting = externalize_supporting_items(manuscript, source)

    tiffs, lines = [], []
    for line in expand_inputs("".join(manuscript), source):
        match = GRAPHICS_PATTERN.match(line)
        if not match:
            lines.append(line)
            continue
        # The graphic is .../figures/source_png/<name>.png; its TIFF sibling was
        # already rendered and size-checked by write_article_artifacts.
        graphic = source / match.group("path")
        tiff = graphic.parent.parent / "source_tiff" / f"{graphic.stem}.tif"
        if not tiff.is_file():
            raise SystemExit(f"{tiff} not found; run `make pull-artifacts` to regenerate figures first.")
        tiffs.append(tiff)
        lines.append(f"{match.group('indent')}% Figure uploaded separately as Fig{len(tiffs)}.tif\n")
    if not tiffs:
        raise SystemExit(f"no active one-line \\includegraphics commands found in {main_tex.name}")

    if output.exists():
        shutil.rmtree(output)
    figures = output / "figures"
    figures.mkdir(parents=True)
    (output / main_tex.name).write_text("".join(lines), encoding="utf-8")
    for name in ("refs.bib", "plos2025.bst"):
        if (source / name).is_file():
            shutil.copy2(source / name, output / name)
    for number, tiff in enumerate(tiffs, 1):
        shutil.copy2(tiff, figures / f"Fig{number}.tif")
    supporting_dir = output / "supporting_information"
    supporting_dir.mkdir(exist_ok=True)
    for name, text in supporting.items():
        (supporting_dir / name).write_text(text, encoding="utf-8")
    print(f"PLOS submission project: {output}")
    print(f"  figures: {len(tiffs)}, supporting items: {len(supporting)}")


if __name__ == "__main__":
    main()
